### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException for single image

### ISSUE THREAD

**Issue by thorstenwagner** [thorstenwagner/ij-nl-means#1]
Applying the filter with default settings (+auto) to image attached give the following exception:
(Fiji Is Just) ImageJ 2.0.0-rc-43/1.50e; Java 1.6.0_24 [64-bit]; Linux 4.2.5-1-ARCH; 147MB of 3179MB (4%)

java.lang.ArrayIndexOutOfBoundsException: 856375
    at de.biomedical_imaging.ij.nlMeansPlugin.NLMeansDenoising_.expandImage(NLMeansDenoising_.java:454)
    at de.biomedical_imaging.ij.nlMeansPlugin.NLMeansDenoising_.NLMeansDenoising(NLMeansDenoising_.java:142)
    at de.biomedical_imaging.ij.nlMeansPlugin.NLMeansDenoising_.run(NLMeansDenoising_.java:122)
    at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:263)
    at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:112)
    at ij.IJ.runUserPlugIn(IJ.java:214)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:136)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Thread.java:662)

![backcorrected_nlm](https://cloud.githubusercontent.com/assets/1113977/11699287/f423d564-9ec3-11e5-8ea2-2778245fe331.png)

**Comment by thorstenwagner** [comment]
Fixed in 1.4.3! Thanks to Pascal Behnel!
